import utils.CurrencyFormatter;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        String amount = args[0];

        CurrencyFormatter currencyFormatter = new CurrencyFormatter();
        
        int target = -5;
        int num = 3;

        target =+ num; // Noncompliant; target = 3

        System.out.println(currencyFormatter.format(amount));
    }
}
